INSERT INTO Team(name) VALUES('Corinthians');
INSERT INTO Team(name) VALUES('Palmeiras');
INSERT INTO Team(name) VALUES('São Paulo');
INSERT INTO Team(name) VALUES('Santos');
INSERT INTO Team(name) VALUES('Santo André');
INSERT INTO Team(name) VALUES('Inter de Limeira');
INSERT INTO Team(name) VALUES('Botafogo SP');
INSERT INTO Team(name) VALUES('Ferroviária');
INSERT INTO Team(name) VALUES('São Bento');
INSERT INTO Team(name) VALUES('Ponte Preta');
INSERT INTO Team(name) VALUES('Bragantino');
INSERT INTO Team(name) VALUES('Ituano');
INSERT INTO Team(name) VALUES('Novorizontino');
INSERT INTO Team(name) VALUES('Mirassol');
INSERT INTO Team(name) VALUES('Guarani');
INSERT INTO Team(name) VALUES('São Caetano');

INSERT INTO Player(name, Team_id, score, status) VALUES('Ivo', 1, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Renato', 1, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Nathan', 1, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Lukinhas', 1, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Lucas', 2, 0, 'PENDENTE');
INSERT INTO Player(name, Team_id, score, status) VALUES('Kenny', 2, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Geyvson', 3, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Leandro', 3, 0, 'OK');
INSERT INTO Player(name, Team_id, score, status) VALUES('Edu', 3, 0, 'OK');
